### ISSUE TITLE
Missing API documentation for alert (definition) profiles

### ISSUE THREAD

**Issue by skateman** [ManageIQ/manageiq-documentation#1190]

**Comment by suyogsainkar** [comment]
@skateman I've created a BZ for this request. https://bugzilla.redhat.com/show_bug.cgi?id=1741367
Could you confirm the version numbers this applies to?

**Comment by skateman** [comment]
From this it seems for hammer, gaprindashvili and ivanchuk ... so I guess all of them.
![Screenshot from 2019-08-15 10-23-32](https://user-images.githubusercontent.com/649130/63082537-c1b52180-bf46-11e9-8cc2-828081ae4ea7.png)

**Comment by chessbyte** [comment]
@skateman @abellotti is this still an issue?

**Comment by skateman** [comment]
Yes, still no docs for this.

**Comment by chessbyte** [comment]
Part of https://github.com/ManageIQ/manageiq-documentation/issues/1441
