### ISSUE TITLE
Cloud provider tags mapping documentation

### ISSUE THREAD

**Issue by gyliu513** [ManageIQ/manageiq-documentation#1436]
FYI @chessbyte @Fryguy @gtanzillo

**Comment by gtanzillo** [comment]
Hi @gyliu513 there are all of the providers that support tag mapping -

Amazon
Azure
Kubernetes
OpenShift
OpenStack

I'll create some documentation with more details, but I wanted to get you the list right away.

**Comment by gyliu513** [comment]
Thanks @gtanzillo , please also mention that 

- We can map native tags to manageiq tags
- But if you create a manageiq tag we don't reverse push that back into the native provider

**Comment by chessbyte** [comment]
@gtanzillo Also please add general documentation around how provider tag mapping works.
