### ISSUE TITLE
Document building a new container image with VMware VixDiskLib Installed for vSphere SmartState

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-documentation#1479]
Due to the VMware redistribution restrictions on the VixDiskLib SDK we cannot simply bundle the library with our appliances or container images.

The customer has to download the VDDK library using their VMware account, accept the VMware terms of service, and install the library on the MIQ filesystem.

For appliances this is relatively easy: https://www.manageiq.org/docs/reference/latest/installing_on_vmware_vsphere/index.html#installing-vmware-vddk-on-manageiq
For podified the customer has to build a container image with this applied on top of our released worker image and tell the operator to use that image for the vmware-operations-worker

**Comment by dehawkins512** [comment]
@agrare Hi Adam,  Are there some steps outlined somewhere I can use to get this doc started?  I'm not familiar with these steps.  Has someone tested this?  re: "build a container image with this applied on top of our released worker image and tell the operator to use that image for the vmware-operations-worker".

**Comment by agrare** [comment]
Hey @dehawkins512 I don't have steps to build the container image but https://access.redhat.com/documentation/en-us/red_hat_cloudforms/5.0/html/installing_red_hat_cloudforms_on_vmware_vsphere/additional-configuration-vmware#installing-vmware-vddk is how to setup vddk on an appliance and will have similar steps except for the container image building part

cc @Fryguy

**Comment by jxadro** [comment]
Which is the operator and the image that should be modified?

**Comment by b1stern** [comment]
@Fryguy @dehawkins512 Have we documented these steps?  I need to get this up and running in my environment.  Can someone walk me through the process?

**Comment by dehawkins512** [comment]
@b1stern I do not have the steps documented yet.
@Fryguy Who can step through this and help Ben, then share the specifics so I can doc?
re: For podified the customer has to build a container image with this applied on top of our released worker image and tell the operator to use that image for the vmware-operations-worker.

**Comment by Fryguy** [comment]
@bdunne @agrare This came up again recently, and I think we have more experience now to help document this.  Can you both together lay out the steps needed (upstream and/or downstream) to create an image with the VDDK, and get it patched into an existing system.  We may also need a note on upgrades _after_ applying the image patch, since the user would have to patch on the next version too.

**Comment by bdunne** [comment]
https://github.com/ManageIQ/manageiq-pods/pull/666
https://github.com/ManageIQ/manageiq-pods/issues/538

**Comment by Fryguy** [comment]
Oh, we need to get that into proper documentation, cause that's hidden where it is.

**Comment by Fryguy** [comment]
@bdunne I guess the problem I see there is that the user has to build it from scratch...I was expecting them to build it on top of an existing "release" image.
