### ISSUE TITLE
Installing on OpenShift Container Platform topic is missing from TOC

### ISSUE THREAD

**Issue by dehawkins512** [ManageIQ/manageiq-documentation#1496]
@chessbyte Should `Installing on OpenShift Container Platform` be included in the ManageIQ TOC?

https://www.manageiq.org/docs/reference/latest/installing_on_openshift_container_platform/

**Comment by chessbyte** [comment]
absolutely!  would be nice to have as many installing on Kubernetes flavors as users validate
