### ISSUE TITLE
Broken links in ManageIQ latest docs

### ISSUE THREAD

**Issue by KhushbuB** [ManageIQ/manageiq-documentation#1497]
For example check latest [Monitoring, alerts and reporting doc](https://www.manageiq.org/docs/reference/latest/monitoring_alerts_and_reporting/index.html) and search for "http" keyword. You will see the broken links.

For example "See <https://access.redhat.com/documentation/en/red-hat-cloudforms/4.7/paged/general-configuration> in the *General Configuration* guide, to learn how to verify the address and validate outgoing email settings." line
Also it refers to Red Hat CloudForms document, which should not be the case.

I can work on this ahead if some one can confirm this issue.

**Comment by Fryguy** [comment]
We noticed that anything inside `<div class="note">` wasn't rebdering properly... @dehawkins512 were you working on that issue?

**Comment by dehawkins512** [comment]
@Fryguy This link is broken on the CF 5.0 docs as well -> https://access.redhat.com/documentation/en-us/red_hat_cloudforms/5.0/html/monitoring_alerts_and_reporting/sect_reports#running_reports
Based on the context, I think this **Note:** should be pointing to https://www.manageiq.org/docs/reference/latest/general_configuration/index.html#outgoing-smtp-email-settings

**Comment by Fryguy** [comment]
@dehawkins512 Yes I agree

**Comment by dehawkins512** [comment]
This issue should be fixed by -> https://github.com/ManageIQ/manageiq-documentation/pull/1498

**Comment by Fryguy** [comment]
#1498 is merged, so we can double check once it's pushed live.

**Comment by Fryguy** [comment]
I believe this is fixed, so closing.  Thanks for reporting @KhushbuB !
