### ISSUE TITLE
[DOC] Missing important guidance for SSO requirements regarding groups

### ISSUE THREAD

**Issue by joshisa** [ManageIQ/manageiq-documentation#1554]
Observation:
A group MUST be pre-defined within Manageiq that matches the group in use on LDAP.  If this group is not pre-defined, redirected logins using SSO may fail.

User Impact:
Understanding configuration pre-requisites to enable SSO correctly can avoid end-user frustration.

**Comment by Fryguy** [comment]
@dehawkins512 I think we should get @jvlcek 's blog posts converted to proper docs - let's discuss when you have some time.
