### ISSUE TITLE
Update PowerVC & PowerVS Cloud Provider Capabilities Matrix

### ISSUE THREAD

**Issue by jaywcarman** [ManageIQ/manageiq-documentation#1563]
The `IBM PowerVC via the OpenStack API` column of the [Cloud Provider Capabilities Matrix](https://www.manageiq.org/docs/reference/latest/capabilities_matrix/index.html#cloud-providers) needs to be updated. There are some capabilities that are incorrectly marked and can be fixed immediately. There's another set of capabilities that _might_ be incorrect - my team has access to a PowerVC environment we can test in. Also, there's a WIP PowerVC provider (subclass of OpenStack) that will be named and branded as `IBM PowerVC`. When it is moved into the public ManageIQ GitHub organization the capability column should be named to match the provider name.

While we're updating PowerVC there are some items we should also check up on in PowerVS (Power Virtual Servers, included in [manageiq-providers-ibm_cloud](https://github.com/manageiq/manageiq-providers-ibm_cloud)).

I'd like to use this issue to track these related TODOs:

- [x] Correct inaccurate `IBM PowerVC via the OpenStack API` information #1564
- [x] Test PowerVC capabilities and update matrix as-needed:
    - Discovery
        - Network Inventory
            - [x] ✔️ Network Managers
            - [x] ✔️ Network Manager Relations
            - [x] ✔️ Network Ports
        - Storage Inventory
            - [x] ✔️ Storage Manager (Cinder Manager w/ Inventory, empty Swift Manager)
        - [x] ❓ Metrics (CPU utilization seems to be collected, so I think "metrics" is ✔️ but the data set is limited)
        - [x] ❌ Forensic Analysis (SmartState)
    - General Features
        - [x] ✔️ ❗ Reporting (doesn't some form of reporting work on _any_ provider?)
        - [x] ❌ Right Sizing (Requires C&U)
    - Operations
        - VM Reconfiguration
            - [x] ✔️ Disk Addition (enabled, but need to verify it works)
- [x] Test PowerVS capabilities and update matrix as-needed:
    - Discovery
        - [x] ❌ Metrics (no workers, C&U not enabled)
        - [x] ❌ [Forensic Analysis (SmartState)](https://access.redhat.com/documentation/en-us/reference_architectures/2017/html/deploying_cloudforms_at_scale/smartstate_analysis)
            - Enable PowerVS CMFR, VM snapshots, etc. required
    - General Features
        - [x] ✔️ ❓ ❗ Instance Genealogy (just shows parent image, is that enough for a ✔️ ?)
        - [x] ❌ Instance Event Timelines (see https://github.com/ManageIQ/guides/blob/master/providers/events.md)
        - [x] ❌ Cloud Layer Timelines (see https://github.com/ManageIQ/guides/blob/master/providers/events.md)
        - [x] ❌ Right Sizing (Requires C&U)
- [x] Update column label to `IBM PowerVC`, new `manageiq-providers-ibm_power_vc` provider is available #1587

### legend:
- [ ] needs testing
- [x] testing complete
- ✔️ feature works
- ❌ feature does *not* work
- ❓ not sure if it worked or not 😕 
- ❗ Capabilities matrix needs to be updated!

fyi: @jwcroppe @dehawkins512 @Kuldip-Nanda

**Comment by agrare** [comment]
@jaywcarman any update on this?  Looks like everything else for morphy is completed: https://github.com/ManageIQ/manageiq-providers-ibm_cloud/issues/269

**Comment by jaywcarman** [comment]
@agrare - I should be able to finish up the last couple of items today, and then submit PRs for the few required changes.
