### ISSUE TITLE
Update providers-overview

### ISSUE THREAD

**Issue by mikebutak** [ManageIQ/manageiq-documentation#1568]
The [providers-overview](https://www.manageiq.org/docs/guides/architecture/providers_overview) omits to mention the "automation provider" as a type of provider.

**Comment by Fryguy** [comment]
From the gitter conversation differentiating the worker types:

Automation Provider: A provider that runs automation playbooks in a fire-and-forget fashion (Ansible; Embedded Ansible; technically ManageIQ Automate too)
Configuration Provider: A system that continuously monitors other systems and modifies their configuration when they change in a desired-state fashion (Puppet; Chef; Foreman's configuration side)
Provisioning Provider: A system that can provision systems and possibly do one-time configuration (Terraform; Foreman's provisioning side)
