### ISSUE TITLE
Document how to add "additional" regions to providers that support that.

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-documentation#1614]
Similarly, we should document how to disable regions.

**Comment by agrare** [comment]
There actually already is documentation on disabling regions for [Amazon](https://github.com/ManageIQ/manageiq-documentation/blob/master/managing_providers/_topics/disabling_amazon_cloud_regions.md) and [Azure](https://github.com/ManageIQ/manageiq-documentation/blob/master/managing_providers/_topics/disabling_azure_cloud_regions.md)

:+1: will add docs on adding additional regions

**Comment by agrare** [comment]
Only Amazon and Azure support additional_regions and disabled_regions in Settings so https://github.com/ManageIQ/manageiq-documentation/pull/1615 will close this

We might want to look at adding that feature to other providers like IBM Cloud however, possibly even move the handling of regions to core and have the providers only bring a yaml file and rake task to update the list

**Comment by Fryguy** [comment]
Yeah I was just thinking that core would be a good place for this.
