### ISSUE TITLE
Broken URLs

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-documentation#1709]
https://www.manageiq.org/docs/guides/external_auth/installation.html
https://www.manageiq.org/docs/guides/external_auth/configuration.html

**Comment by Fryguy** [comment]
@tjyang Those docs do not exist in the source repo either, so I wouldn't expect them to exist.  Where do you see these links?

**Comment by tjyang** [comment]
When I was reading and clicking around the https://www.manageiq.org/docs/ web site.  I don't remember exactly where. Will update to see if I can reproduce later.

**Comment by Fryguy** [comment]
ok, closing for now.  Please reopen if you find them
