### ISSUE TITLE
Adding URL to link back to real doc site

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-documentation#1711]
Hi

Please add "https://www.manageiq.org/docs/". It is under this project's About button.  

- Before
![image](https://user-images.githubusercontent.com/378638/211325902-69996026-6851-4300-8102-d736ae0c5eff.png)

- After
![image](https://user-images.githubusercontent.com/378638/211326596-1941b260-fe72-427d-ba1d-1c3c246110c9.png)

**Comment by Fryguy** [comment]
Done.  Thanks!
