### ISSUE TITLE
Root-level docs are not rendering

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-documentation#1723]
There are a handful of .md files at the root level[^1] that are not rendering.  I'm not sure if we should fix things to make them render, or if they are in the wrong location.  @agrare Do you recognize these?  Most of them seem provider oriented.

[^1]: https://github.com/search?q=repo%3AManageIQ%2Fmanageiq-documentation+path%3A%2F*.md&type=code&ref=advsearch

**Comment by agrare** [comment]
I've never seen these before, they were created by https://github.com/ManageIQ/manageiq-documentation/pull/1580 with 34 helpful "Add files via upload" commits :)

I'm not sure where they were supposed to be without knowing where they came from.

**Comment by Fryguy** [comment]
Oh weird - I wonder if these were accidental commits with a big `git add .`, and were work in progress files or something.  @rwellon, were you making changes to these files?

**Comment by Fryguy** [comment]
@dehawkins512 Perhaps you know why they were introduced?

**Comment by agrare** [comment]
These might be duplicates?

There is https://github.com/ManageIQ/manageiq-documentation/blob/2eda4ad230b059ad945dfab864e200ea22768296/managing_infrastructure_and_inventory/_topics/deleting_a_router.md

Need to check if all of the top-level files have dups

**Comment by agrare** [comment]
Yes all of these also exist in `./managing_infrastructure_and_inventory/_topics` with no changes to simple formatting changes.  I'll put in a PR to delete the top-level files

```
./managing_infrastructure_and_inventory/_topics/controlling_power_state_of_rhv_vms.md
./controlling_power_state_of_rhv_vms.md

./managing_infrastructure_and_inventory/_topics/controlling_the_power_state_of_an_instance.md
./controlling_the_power_state_of_an_instance.md

./managing_infrastructure_and_inventory/_topics/deleting_a_security_group.md
./deleting_a_security_group.md

./managing_infrastructure_and_inventory/_topics/instance_evacuation.md
./instance_evacuation.md

./managing_infrastructure_and_inventory/_topics/instance_live_migration.md
./instance_live_migration.md

./managing_infrastructure_and_inventory/_topics/viewing_a_user_information_for_an_instance_or_image.md
./viewing_a_user_information_for_an_instance_or_image.md

./managing_infrastructure_and_inventory/_topics/viewing_availability_zone_relationships.md
./viewing_availability_zone_relationships.md
```

**Comment by dehawkins512** [comment]
@Fryguy @agrare 
Yes, I can clean these up.  The files in the top level have the updated navigation.  Connor helped update these and I committed the PRs and missed they were going to top level instead of the correct location / folders.
