### ISSUE TITLE
Need more documentation for external Postgres

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-documentation#530]
https://github.com/ManageIQ/manageiq_docs/blob/master/common/configuration.adoc has a lot, but it's slightly wrong if the user wants the replication feature.  If the user wishes to leverage the replication features of ManageIQ, then the user must install SCL's Postgres 9.5, and the pglogical/repmgr RPMs.  We should mention that an alternate approach for an external database is to just launch another appliance and set it up to be database only.

cc @carbonin Can you verify what I'm saying to keep me honest

cc @adahms @cbudz

**Comment by carbonin** [comment]
Sounds about right to me @Fryguy

**Comment by chessbyte** [comment]
Is this still a valid issue?

**Comment by carbonin** [comment]
That link is gone, but I assume it was something like [this](https://github.com/ManageIQ/manageiq-documentation/blob/483346ace4775ce7c8094c0cf22cc38668189339/general_configuration/_topics/configuration.md#configuring-database-replication-and-centralized-administration)?

If so I guess it's still valid, but I don't think we talk about external databases anywhere in these docs so it's far from trivial.
