### ISSUE TITLE
Documentation under Bell icon is not linked directly

### ISSUE THREAD

**Issue by tjyang** [ManageIQ/manageiq-documentation#557]
See below, when one click on "Documentation" , it is showing "
For questions or problem reporting, visit ManageIQ.org "

![image](https://user-images.githubusercontent.com/378638/32177206-b4ec4a8e-bd57-11e7-93ca-608d983b188f.png)

I am hoping to reach http://www.manageiq.org/docs/ directly.

**Comment by chessbyte** [comment]
@himdel @h-kataria is this issue still valid?

**Comment by h-kataria** [comment]
@chessbyte that's a valid issue

**Comment by himdel** [comment]
I think so... we have..

Documentation - hardcoded to `/support/index?support_tab=about`
ManageIQ.org - using `Settings.docs.product_support_website`, meaning `http://www.manageiq.org` by default
About - the about modal

So, we do have links to manageiq.org.
But our Documentation link leads to an in-app page linking the pdf docs.

**Comment by chessbyte** [comment]
@himdel do you know if the ManageIQ appliance includes the pdf docs that we link to?

**Comment by tjyang** [comment]
- This is from  ivanchuck-4 vmware appliance.

![image](https://user-images.githubusercontent.com/378638/78919207-38170e80-7a57-11ea-80f5-6520d93d461c.png)
-  mangeiq.org URL above in picture  is linking to http://www.manageiq.org , not https://www.manageiq.org/docs/

**Comment by himdel** [comment]
Aah, that would be a no, then.

The screen will add the links as long as `#{Rails.root}/public/doc/*.pdf` exists,
but without any pdf links,it just has the title and that one line.

**Comment by himdel** [comment]
Seems like our `/support/index?support_tab=about` Documentation page is pretty useless without the PDFs, so, what about:

* we add `Settings.docs.product_documentation_website`, for the Documentation link, defaulting to `https://www.manageiq.org/docs/` upstream
* override the setting to `/support/index?support_tab=about` when distributing with PDFs

**Comment by chessbyte** [comment]
@himdel, I like that!

@Fryguy @h-kataria what do you think?

**Comment by h-kataria** [comment]
> Seems like our `/support/index?support_tab=about` Documentation page is pretty useless without the PDFs, so, what about:
> 
>     * we add `Settings.docs.product_documentation_website`, for the Documentation link, defaulting to `https://www.manageiq.org/docs/` upstream
> 
>     * override the setting to `/support/index?support_tab=about` when distributing with PDFs

I like the idea.

**Comment by Fryguy** [comment]
Sounds good to me.  Only thing is that it's kind of weird to have to know this weird url fragment, and if we change it later we have to sync the value in two places.  Can we instead have something like a `Settings.docs.link_target = link` be the default which shows the `Settings.docs.product_documentation_website`, and then it can be overridden with  `Settings.docs.link_target = tab` which allows the tab and the PDFs and the link inside?

Even simpler would be no configuration at all, and if the PDFs are detected show the tab, otherwise only show the link.

**Comment by himdel** [comment]
Makes sense :)

Using 
`Settings.docs.product_documentation_direct_link` = true/false (false means the old screen, defaults to true)
`Settings.docs.product_documentation_website` = https://www.manageiq.org/docs/

https://github.com/ManageIQ/manageiq/pull/20320
https://github.com/ManageIQ/manageiq-ui-classic/pull/7162
