### ISSUE TITLE
Link of packages from "Ubuntu fix for failing Bundler" need to be updated

### ISSUE THREAD

**Issue by abhinav1592** [ManageIQ/manageiq-documentation#627]
In [Developer setup for ManageIQ for Ubuntu](http://manageiq.org/docs/guides/developer_setup.html),
in the section "Ubuntu fix for failing Bundler", the packages no longer point to correct location.

Original:
sudo apt remove libssl-dev
wget http://ftp.cz.debian.org/debian/pool/main/o/openssl1.0/libssl1.0-dev_1.0.2l-2_amd64.deb
wget http://ftp.cz.debian.org/debian/pool/main/o/openssl1.0/libssl1.0.2_1.0.2l-2_amd64.deb
sudo dpkg -i libssl1.0-dev_1.0.2l-2_amd64.deb libssl1.0.2_1.0.2l-2_amd64.deb

Modified version:
sudo apt remove libssl-dev
wget http://cdn-fastly.deb.debian.org/debian/pool/main/o/openssl1.0/libssl1.0-dev_1.0.2l-2+deb9u1_amd64.deb
wget http://cdn-fastly.deb.debian.org/debian/pool/main/o/openssl1.0/libssl1.0.2_1.0.2l-2+deb9u1_amd64.deb
sudo dpkg -i libssl1.0-dev_1.0.2l-2+deb9u1_amd64.deb libssl1.0.2_1.0.2l-2+deb9u1_amd64.deb

**Comment by chessbyte** [comment]
No longer see this in the docs.  Must have been fixed.
